# Programs
$terminal = foot
$editor = nvim
$launcher = walker
$clipboard = cliphist
$browser = helium-browser
$screenshot = hyprshot

# Colors
$BD_COL_ACTIVE = rgb(b2d3dd)
$BD_COL_INACTIVE = rgb(a6a9a9)
$BD_COL_GROUP = rgb(696874)

$SH_COL_ACTIVE = rgba(060607AA)
$SH_COL_INACTIVE = rgba(06060754)
