windowrule {
  name = tui_settings
  match:title = impala||bluetui
  float = 1
  center = 1
  size = 900 600
}

windowrule {
  name = firefox_pip
  match:class = firefox
  match:title = Picture-in-Picture
  float = 1
  border_size = 0
}
