vim.pack.add({
    --    { src = "https://github.com/EdenEast/nightfox.nvim" },
    --    { src = "https://github.com/zootedb0t/citruszest.nvim" },
    { src = "https://github.com/dgox16/oldworld.nvim" },
    { src = "https://github.com/nvim-tree/nvim-tree.lua" },
    { src = "https://github.com/neovim/nvim-lspconfig" },
    { src = "https://github.com/nvim-tree/nvim-web-devicons" },
    { src = "https://github.com/Saghen/blink.cmp" },
    { src = "https://github.com/romgrk/barbar.nvim" },
    { src = "https://github.com/mrcjkb/rustaceanvim" },
    { src = "https://github.com/nvim-treesitter/nvim-treesitter" },
    { src = "https://github.com/elkowar/yuck.vim" },
    { src = "https://github.com/gpanders/nvim-parinfer" },
    { src = "https://github.com/nvimtools/none-ls.nvim" },
    { src = "https://github.com/nvim-lua/plenary.nvim" },
    { src = "https://github.com/mfussenegger/nvim-jdtls" },
})
